#!/bin/sh

export ZFS_BACKUP_S3_REGION=***
export ZFS_BACKUP_S3_ACCESS_KEY_ID=***
export ZFS_BACKUP_S3_SECRET_ACCESS_KEY=***
export ZFS_BACKUP_S3_FULL_PREFIX=***
export ZFS_BACKUP_S3_FULL_STORAGE_CLASS=***
export ZFS_BACKUP_S3_MAX_S3_PART_SIZE=***
export ZFS_BACKUP_S3_MAX_FILE_SIZE=***
export ZFS_BACKUP_S3_TEMP_DIR=***